version: '3'

services:
  app:
    build: 
      context: app/
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - tarantool

  tarantool:
    build: 
      context: tarantool-sql/
      dockerfile: Dockerfile
    ports:
      - '3301:3301'
    volumes:
      - ./tarantool_data/:/var/lib/tarantool
